package com.indizen.cursoSpring.servicio.persistence.grouppermission;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.indizen.cursoSpring.servicio.model.grouppermission.GroupPermission;
import com.indizen.cursoSpring.servicio.model.grouppermission.GroupPermissionExample;
import com.indizen.cursoSpring.servicio.persistence.PaginationContext;

@Repository("groupPermissionDAO")
public class GroupPermissionDAOImpl extends SqlMapClientDaoSupport implements GroupPermissionDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    @Autowired
public GroupPermissionDAOImpl(SqlMapClient sqlMapClient) {
        setSqlMapClient(sqlMapClient);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int countByExample(GroupPermissionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_group_permission.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int deleteByExample(GroupPermissionExample example) {
        int rows = getSqlMapClientTemplate().delete("t_group_permission.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        GroupPermission _key = new GroupPermission();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_group_permission.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer insert(GroupPermission record) {
        Object newKey = getSqlMapClientTemplate().insert("t_group_permission.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer insertSelective(GroupPermission record) {
        Object newKey = getSqlMapClientTemplate().insert("t_group_permission.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public List selectByExample(GroupPermissionExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_group_permission.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public GroupPermission selectByPrimaryKey(Integer id) {
        GroupPermission _key = new GroupPermission();
        _key.setId(id);
        GroupPermission record = (GroupPermission) getSqlMapClientTemplate().queryForObject("t_group_permission.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int updateByExampleSelective(GroupPermission record, GroupPermissionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_group_permission.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int updateByExample(GroupPermission record, GroupPermissionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_group_permission.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int updateByPrimaryKeySelective(GroupPermission record) {
        int rows = getSqlMapClientTemplate().update("t_group_permission.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int updateByPrimaryKey(GroupPermission record) {
        int rows = getSqlMapClientTemplate().update("t_group_permission.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    protected static class UpdateByExampleParms extends GroupPermissionExample {
        private Object record;

        public UpdateByExampleParms(Object record, GroupPermissionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
	/**
    * Selecciona un conjunto de resultados basados en un ejemplo y 
    * los pagina.
    * @param example Objeto de ejemplo para la query
    * @param paginationContext Objeto utilizado para controlar la paginación
    * @return lista de elementos pertenecientes a la página correspondiente
    */
    public List<GroupPermission> selectByExamplePaginated(GroupPermissionExample example, PaginationContext paginationContext) {
    	assert paginationContext.getSkipResults() >= 0;
		assert paginationContext.getMaxResults() >= 0;
		
		final List<GroupPermission> result = new ArrayList<GroupPermission>();
		
		//Obtiene y actualiza el número total de resultados del ejemplo
		paginationContext.updateTotalCount((Integer) countByExample(example));
	
		//iBatis hace la paginación física de los resultados usando un cursos
		//si está disponible la función ResultSet.absolute(position);
		final List<GroupPermission> queryForList = getSqlMapClientTemplate().queryForList("t_group_permission.selectByExample", 
				example,paginationContext.getSkipResults(),
				paginationContext.getMaxResults());	
		result.addAll(queryForList);
		return Collections.unmodifiableList(result);     
    }	
	
	/**
	 * 
	 * Borra todos los datos de la tabla
	 * 
	 */
	public void deleteAllData(){
		getSqlMapClientTemplate().delete("t_group_permission.trucate_table");
	}
   
}
