package com.indizen.cursoSpring.servicio.persistence.grouppermission;

import java.util.List;

import com.indizen.cursoSpring.servicio.model.grouppermission.GroupPermission;
import com.indizen.cursoSpring.servicio.model.grouppermission.GroupPermissionExample;
import com.indizen.cursoSpring.servicio.persistence.PersistenceBase;
public interface GroupPermissionDAO extends PersistenceBase<GroupPermission, GroupPermissionExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int countByExample(GroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int deleteByExample(GroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    Integer insert(GroupPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    Integer insertSelective(GroupPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    List selectByExample(GroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    GroupPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int updateByExampleSelective(GroupPermission record, GroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int updateByExample(GroupPermission record, GroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int updateByPrimaryKeySelective(GroupPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int updateByPrimaryKey(GroupPermission record);
}
