package com.indizen.cursoSpring.servicio.model.vusergroup;

import java.io.Serializable;

import com.indizen.cursoSpring.servicio.model.EntityBase;
public class VUserGroup implements Serializable,EntityBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_group.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_group.id_user
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer idUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_group.name_user
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private String nameUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_group.id_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer idGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user_group.name_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private String nameGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_group.id
     *
     * @return the value of v_user_group.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_group.id
     *
     * @param id the value for v_user_group.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_group.id_user
     *
     * @return the value of v_user_group.id_user
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_group.id_user
     *
     * @param idUser the value for v_user_group.id_user
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_group.name_user
     *
     * @return the value of v_user_group.name_user
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public String getNameUser() {
        return nameUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_group.name_user
     *
     * @param nameUser the value for v_user_group.name_user
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setNameUser(String nameUser) {
        this.nameUser = nameUser == null ? null : nameUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_group.id_group
     *
     * @return the value of v_user_group.id_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getIdGroup() {
        return idGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_group.id_group
     *
     * @param idGroup the value for v_user_group.id_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setIdGroup(Integer idGroup) {
        this.idGroup = idGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user_group.name_group
     *
     * @return the value of v_user_group.name_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public String getNameGroup() {
        return nameGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user_group.name_group
     *
     * @param nameGroup the value for v_user_group.name_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setNameGroup(String nameGroup) {
        this.nameGroup = nameGroup == null ? null : nameGroup.trim();
    }
}
