package com.indizen.cursoSpring.servicio.model.grouppermission;

import java.io.Serializable;

import com.indizen.cursoSpring.servicio.model.EntityBase;
public class GroupPermission implements Serializable,EntityBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_permission.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_permission.id_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer idGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_permission.id_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer idPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_permission.id
     *
     * @return the value of t_group_permission.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_permission.id
     *
     * @param id the value for t_group_permission.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_permission.id_group
     *
     * @return the value of t_group_permission.id_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getIdGroup() {
        return idGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_permission.id_group
     *
     * @param idGroup the value for t_group_permission.id_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setIdGroup(Integer idGroup) {
        this.idGroup = idGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_permission.id_permission
     *
     * @return the value of t_group_permission.id_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getIdPermission() {
        return idPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_permission.id_permission
     *
     * @param idPermission the value for t_group_permission.id_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setIdPermission(Integer idPermission) {
        this.idPermission = idPermission;
    }
}
