package com.indizen.cursoSpring.servicio.persistence.vusergroup;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.indizen.cursoSpring.servicio.model.vusergroup.VUserGroup;
import com.indizen.cursoSpring.servicio.model.vusergroup.VUserGroupExample;
import com.indizen.cursoSpring.servicio.persistence.PaginationContext;

@Repository("vUserGroupDAO")
public class VUserGroupDAOImpl extends SqlMapClientDaoSupport implements VUserGroupDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    @Autowired
public VUserGroupDAOImpl(SqlMapClient sqlMapClient) {
        setSqlMapClient(sqlMapClient);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int countByExample(VUserGroupExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("v_user_group.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int deleteByExample(VUserGroupExample example) {
        int rows = getSqlMapClientTemplate().delete("v_user_group.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer insert(VUserGroup record) {
        Object newKey = getSqlMapClientTemplate().insert("v_user_group.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer insertSelective(VUserGroup record) {
        Object newKey = getSqlMapClientTemplate().insert("v_user_group.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public List selectByExample(VUserGroupExample example) {
        List list = getSqlMapClientTemplate().queryForList("v_user_group.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int updateByExampleSelective(VUserGroup record, VUserGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("v_user_group.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int updateByExample(VUserGroup record, VUserGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("v_user_group.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    protected static class UpdateByExampleParms extends VUserGroupExample {
        private Object record;

        public UpdateByExampleParms(Object record, VUserGroupExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
	/**
    * Selecciona un conjunto de resultados basados en un ejemplo y 
    * los pagina.
    * @param example Objeto de ejemplo para la query
    * @param paginationContext Objeto utilizado para controlar la paginación
    * @return lista de elementos pertenecientes a la página correspondiente
    */
    public List<VUserGroup> selectByExamplePaginated(VUserGroupExample example, PaginationContext paginationContext) {
    	assert paginationContext.getSkipResults() >= 0;
		assert paginationContext.getMaxResults() >= 0;
		
		final List<VUserGroup> result = new ArrayList<VUserGroup>();
		
		//Obtiene y actualiza el número total de resultados del ejemplo
		paginationContext.updateTotalCount((Integer) countByExample(example));
	
		//iBatis hace la paginación física de los resultados usando un cursos
		//si está disponible la función ResultSet.absolute(position);
		final List<VUserGroup> queryForList = getSqlMapClientTemplate().queryForList("v_user_group.selectByExample", 
				example,paginationContext.getSkipResults(),
				paginationContext.getMaxResults());	
		result.addAll(queryForList);
		return Collections.unmodifiableList(result);     
    }	
	
	/**
	 * 
	 * Borra todos los datos de la tabla
	 * 
	 */
	public void deleteAllData(){
		getSqlMapClientTemplate().delete("v_user_group.trucate_table");
	}
   
}
