package com.indizen.cursoSpring.servicio.persistence.vusergroup;

import java.util.List;

import com.indizen.cursoSpring.servicio.model.vusergroup.VUserGroup;
import com.indizen.cursoSpring.servicio.model.vusergroup.VUserGroupExample;
import com.indizen.cursoSpring.servicio.persistence.PersistenceBase;
public interface VUserGroupDAO extends PersistenceBase<VUserGroup, VUserGroupExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int countByExample(VUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int deleteByExample(VUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    Integer insert(VUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    Integer insertSelective(VUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    List selectByExample(VUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int updateByExampleSelective(VUserGroup record, VUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int updateByExample(VUserGroup record, VUserGroupExample example);
}
