package com.indizen.cursoSpring.servicio.model.user;

import java.io.Serializable;
import java.util.Date;

import com.indizen.cursoSpring.servicio.model.EntityBase;
public class User implements Serializable,EntityBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.surname1
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private String surname1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.telephone
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.enable
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.blocked
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer blocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.attempts_login
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer attemptsLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.surname2
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private String surname2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.date_last_password
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Date dateLastPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.date_last_login
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Date dateLastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.name
     *
     * @return the value of t_user.name
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.name
     *
     * @param name the value for t_user.name
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.surname1
     *
     * @return the value of t_user.surname1
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public String getSurname1() {
        return surname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.surname1
     *
     * @param surname1 the value for t_user.surname1
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setSurname1(String surname1) {
        this.surname1 = surname1 == null ? null : surname1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.telephone
     *
     * @return the value of t_user.telephone
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.telephone
     *
     * @param telephone the value for t_user.telephone
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.enable
     *
     * @return the value of t_user.enable
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.enable
     *
     * @param enable the value for t_user.enable
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.blocked
     *
     * @return the value of t_user.blocked
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getBlocked() {
        return blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.blocked
     *
     * @param blocked the value for t_user.blocked
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setBlocked(Integer blocked) {
        this.blocked = blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.attempts_login
     *
     * @return the value of t_user.attempts_login
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getAttemptsLogin() {
        return attemptsLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.attempts_login
     *
     * @param attemptsLogin the value for t_user.attempts_login
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setAttemptsLogin(Integer attemptsLogin) {
        this.attemptsLogin = attemptsLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.surname2
     *
     * @return the value of t_user.surname2
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public String getSurname2() {
        return surname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.surname2
     *
     * @param surname2 the value for t_user.surname2
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setSurname2(String surname2) {
        this.surname2 = surname2 == null ? null : surname2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.date_last_password
     *
     * @return the value of t_user.date_last_password
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Date getDateLastPassword() {
        return dateLastPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.date_last_password
     *
     * @param dateLastPassword the value for t_user.date_last_password
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setDateLastPassword(Date dateLastPassword) {
        this.dateLastPassword = dateLastPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.date_last_login
     *
     * @return the value of t_user.date_last_login
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Date getDateLastLogin() {
        return dateLastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.date_last_login
     *
     * @param dateLastLogin the value for t_user.date_last_login
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setDateLastLogin(Date dateLastLogin) {
        this.dateLastLogin = dateLastLogin;
    }
}
