package com.indizen.cursoSpring.servicio.persistence.vgrouppermission;

import java.util.List;

import com.indizen.cursoSpring.servicio.model.vgrouppermission.VGroupPermission;
import com.indizen.cursoSpring.servicio.model.vgrouppermission.VGroupPermissionExample;
import com.indizen.cursoSpring.servicio.persistence.PersistenceBase;
public interface VGroupPermissionDAO extends PersistenceBase<VGroupPermission, VGroupPermissionExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int countByExample(VGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int deleteByExample(VGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    Integer insert(VGroupPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    Integer insertSelective(VGroupPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    List selectByExample(VGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int updateByExampleSelective(VGroupPermission record, VGroupPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    int updateByExample(VGroupPermission record, VGroupPermissionExample example);
}
