package com.indizen.cursoSpring.servicio.persistence.rest;

import java.util.List;

import com.indizen.cursoSpring.servicio.model.rest.Rest;
import com.indizen.cursoSpring.servicio.model.rest.RestExample;
import com.indizen.cursoSpring.servicio.persistence.PersistenceBase;
public interface RestDAO extends PersistenceBase<Rest, RestExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    int countByExample(RestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    int deleteByExample(RestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    Integer insert(Rest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    Integer insertSelective(Rest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    List selectByExample(RestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    Rest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    int updateByExampleSelective(Rest record, RestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    int updateByExample(Rest record, RestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    int updateByPrimaryKeySelective(Rest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    int updateByPrimaryKey(Rest record);
}
