package com.indizen.cursoSpring.servicio.persistence.rest;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.indizen.cursoSpring.servicio.model.rest.Rest;
import com.indizen.cursoSpring.servicio.model.rest.RestExample;
import com.indizen.cursoSpring.servicio.persistence.PaginationContext;

@Repository("restDAO")
public class RestDAOImpl extends SqlMapClientDaoSupport implements RestDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    @Autowired
public RestDAOImpl(SqlMapClient sqlMapClient) {
        setSqlMapClient(sqlMapClient);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    public int countByExample(RestExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_rest.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    public int deleteByExample(RestExample example) {
        int rows = getSqlMapClientTemplate().delete("t_rest.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        Rest _key = new Rest();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_rest.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    public Integer insert(Rest record) {
        Object newKey = getSqlMapClientTemplate().insert("t_rest.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    public Integer insertSelective(Rest record) {
        Object newKey = getSqlMapClientTemplate().insert("t_rest.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    public List selectByExample(RestExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_rest.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    public Rest selectByPrimaryKey(Integer id) {
        Rest _key = new Rest();
        _key.setId(id);
        Rest record = (Rest) getSqlMapClientTemplate().queryForObject("t_rest.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    public int updateByExampleSelective(Rest record, RestExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_rest.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    public int updateByExample(Rest record, RestExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_rest.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    public int updateByPrimaryKeySelective(Rest record) {
        int rows = getSqlMapClientTemplate().update("t_rest.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    public int updateByPrimaryKey(Rest record) {
        int rows = getSqlMapClientTemplate().update("t_rest.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_rest
     *
     * @mbggenerated Fri Apr 20 10:00:45 CEST 2012
     */
    protected static class UpdateByExampleParms extends RestExample {
        private Object record;

        public UpdateByExampleParms(Object record, RestExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
	/**
    * Selecciona un conjunto de resultados basados en un ejemplo y 
    * los pagina.
    * @param example Objeto de ejemplo para la query
    * @param paginationContext Objeto utilizado para controlar la paginación
    * @return lista de elementos pertenecientes a la página correspondiente
    */
    public List<Rest> selectByExamplePaginated(RestExample example, PaginationContext paginationContext) {
    	assert paginationContext.getSkipResults() >= 0;
		assert paginationContext.getMaxResults() >= 0;
		
		final List<Rest> result = new ArrayList<Rest>();
		
		//Obtiene y actualiza el número total de resultados del ejemplo
		paginationContext.updateTotalCount((Integer) countByExample(example));
	
		//iBatis hace la paginación física de los resultados usando un cursos
		//si está disponible la función ResultSet.absolute(position);
		final List<Rest> queryForList = getSqlMapClientTemplate().queryForList("t_rest.selectByExample", 
				example,paginationContext.getSkipResults(),
				paginationContext.getMaxResults());	
		result.addAll(queryForList);
		return Collections.unmodifiableList(result);     
    }	
	
	/**
	 * 
	 * Borra todos los datos de la tabla
	 * 
	 */
	public void deleteAllData(){
		getSqlMapClientTemplate().delete("t_rest.trucate_table");
	}
   
}
