package com.indizen.cursoSpring.servicio.persistence.permission;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.indizen.cursoSpring.servicio.model.permission.Permission;
import com.indizen.cursoSpring.servicio.model.permission.PermissionExample;
import com.indizen.cursoSpring.servicio.persistence.PaginationContext;

@Repository("permissionDAO")
public class PermissionDAOImpl extends SqlMapClientDaoSupport implements PermissionDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    @Autowired
public PermissionDAOImpl(SqlMapClient sqlMapClient) {
        setSqlMapClient(sqlMapClient);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int countByExample(PermissionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_permission.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int deleteByExample(PermissionExample example) {
        int rows = getSqlMapClientTemplate().delete("t_permission.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        Permission _key = new Permission();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_permission.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer insert(Permission record) {
        Object newKey = getSqlMapClientTemplate().insert("t_permission.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer insertSelective(Permission record) {
        Object newKey = getSqlMapClientTemplate().insert("t_permission.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public List selectByExample(PermissionExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_permission.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Permission selectByPrimaryKey(Integer id) {
        Permission _key = new Permission();
        _key.setId(id);
        Permission record = (Permission) getSqlMapClientTemplate().queryForObject("t_permission.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int updateByExampleSelective(Permission record, PermissionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_permission.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int updateByExample(Permission record, PermissionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_permission.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int updateByPrimaryKeySelective(Permission record) {
        int rows = getSqlMapClientTemplate().update("t_permission.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public int updateByPrimaryKey(Permission record) {
        int rows = getSqlMapClientTemplate().update("t_permission.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    protected static class UpdateByExampleParms extends PermissionExample {
        private Object record;

        public UpdateByExampleParms(Object record, PermissionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
	/**
    * Selecciona un conjunto de resultados basados en un ejemplo y 
    * los pagina.
    * @param example Objeto de ejemplo para la query
    * @param paginationContext Objeto utilizado para controlar la paginación
    * @return lista de elementos pertenecientes a la página correspondiente
    */
    public List<Permission> selectByExamplePaginated(PermissionExample example, PaginationContext paginationContext) {
    	assert paginationContext.getSkipResults() >= 0;
		assert paginationContext.getMaxResults() >= 0;
		
		final List<Permission> result = new ArrayList<Permission>();
		
		//Obtiene y actualiza el número total de resultados del ejemplo
		paginationContext.updateTotalCount((Integer) countByExample(example));
	
		//iBatis hace la paginación física de los resultados usando un cursos
		//si está disponible la función ResultSet.absolute(position);
		final List<Permission> queryForList = getSqlMapClientTemplate().queryForList("t_permission.selectByExample", 
				example,paginationContext.getSkipResults(),
				paginationContext.getMaxResults());	
		result.addAll(queryForList);
		return Collections.unmodifiableList(result);     
    }	
	
	/**
	 * 
	 * Borra todos los datos de la tabla
	 * 
	 */
	public void deleteAllData(){
		getSqlMapClientTemplate().delete("t_permission.trucate_table");
	}
   
}
