package com.indizen.cursoSpring.servicio.model.vgrouppermission;

import java.io.Serializable;

import com.indizen.cursoSpring.servicio.model.EntityBase;
public class VGroupPermission implements Serializable,EntityBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_group_permission.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_group_permission.id_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer idGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_group_permission.name_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private String nameGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_group_permission.id_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private Integer idPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_group_permission.name_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private String namePermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_group_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_group_permission.id
     *
     * @return the value of v_group_permission.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_group_permission.id
     *
     * @param id the value for v_group_permission.id
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_group_permission.id_group
     *
     * @return the value of v_group_permission.id_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getIdGroup() {
        return idGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_group_permission.id_group
     *
     * @param idGroup the value for v_group_permission.id_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setIdGroup(Integer idGroup) {
        this.idGroup = idGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_group_permission.name_group
     *
     * @return the value of v_group_permission.name_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public String getNameGroup() {
        return nameGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_group_permission.name_group
     *
     * @param nameGroup the value for v_group_permission.name_group
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setNameGroup(String nameGroup) {
        this.nameGroup = nameGroup == null ? null : nameGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_group_permission.id_permission
     *
     * @return the value of v_group_permission.id_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public Integer getIdPermission() {
        return idPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_group_permission.id_permission
     *
     * @param idPermission the value for v_group_permission.id_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setIdPermission(Integer idPermission) {
        this.idPermission = idPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_group_permission.name_permission
     *
     * @return the value of v_group_permission.name_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public String getNamePermission() {
        return namePermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_group_permission.name_permission
     *
     * @param namePermission the value for v_group_permission.name_permission
     *
     * @mbggenerated Fri Apr 27 11:35:15 CEST 2012
     */
    public void setNamePermission(String namePermission) {
        this.namePermission = namePermission == null ? null : namePermission.trim();
    }
}
